language: php
php:
  - 5.6.4
  - 7.0

install:
  - travis_retry composer self-update 1.0.0-alpha10

before_script:
  - travis_retry composer update --dev --no-interaction

script:
  - vendor/bin/phpunit
